// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tkpt.proto

package api_tpkt_service

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/googleapis/api/httpbody"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type About struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *About) Reset()         { *m = About{} }
func (m *About) String() string { return proto.CompactTextString(m) }
func (*About) ProtoMessage()    {}
func (*About) Descriptor() ([]byte, []int) {
	return fileDescriptor_24b6daffab0041e4, []int{0}
}

func (m *About) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_About.Unmarshal(m, b)
}
func (m *About) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_About.Marshal(b, m, deterministic)
}
func (m *About) XXX_Merge(src proto.Message) {
	xxx_messageInfo_About.Merge(m, src)
}
func (m *About) XXX_Size() int {
	return xxx_messageInfo_About.Size(m)
}
func (m *About) XXX_DiscardUnknown() {
	xxx_messageInfo_About.DiscardUnknown(m)
}

var xxx_messageInfo_About proto.InternalMessageInfo

func (m *About) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*About)(nil), "api.tpkt_service.About")
}

func init() { proto.RegisterFile("tkpt.proto", fileDescriptor_24b6daffab0041e4) }

var fileDescriptor_24b6daffab0041e4 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x86, 0xa5, 0x46, 0xc5, 0x8d, 0x12, 0x52, 0xa2, 0x60, 0xf1, 0x00, 0x78, 0x31, 0x46, 0x76,
	0x03, 0x3e, 0x41, 0x35, 0xc4, 0x10, 0x2e, 0x04, 0x88, 0x31, 0x5e, 0xcc, 0x6e, 0x59, 0xcb, 0x02,
	0xee, 0x4e, 0xda, 0x29, 0x06, 0x8f, 0x3e, 0x82, 0x3e, 0x9a, 0xaf, 0xe0, 0x83, 0x18, 0xb6, 0x6d,
	0xa2, 0xc6, 0xdb, 0x4c, 0xbe, 0xf9, 0x66, 0x76, 0x7f, 0x42, 0x70, 0x01, 0x48, 0x21, 0x32, 0x68,
	0xdc, 0x32, 0x07, 0x45, 0x11, 0x16, 0xf8, 0x18, 0xcb, 0x68, 0xa5, 0x02, 0xe9, 0x5d, 0x5a, 0x10,
	0xb4, 0x43, 0xa9, 0xdb, 0xf1, 0x0b, 0x0f, 0x43, 0x19, 0x31, 0x03, 0xa8, 0x8c, 0x8e, 0x19, 0xd7,
	0xda, 0x20, 0xb7, 0x75, 0xea, 0x7b, 0xa7, 0xa1, 0x31, 0xe1, 0x52, 0x32, 0x0e, 0xea, 0x1f, 0x5a,
	0x5d, 0xf1, 0xa5, 0x9a, 0x72, 0x94, 0x2c, 0x2f, 0x32, 0x50, 0xcf, 0x34, 0xdb, 0x89, 0xe4, 0x89,
	0xc9, 0x67, 0xc0, 0x75, 0x06, 0x4f, 0x7e, 0xec, 0x9c, 0x21, 0x82, 0x30, 0xd3, 0x0c, 0xb5, 0x9a,
	0x64, 0xc7, 0x17, 0x26, 0x41, 0xb7, 0x46, 0xf6, 0x02, 0xa3, 0x51, 0x6a, 0xac, 0x15, 0x1a, 0x85,
	0xf3, 0xfd, 0x51, 0xde, 0x76, 0xe7, 0xa4, 0x34, 0x59, 0x00, 0x8e, 0xd3, 0xef, 0xf8, 0xc3, 0xbe,
	0x7b, 0x4f, 0x8a, 0xb7, 0x12, 0x53, 0xef, 0x98, 0xa6, 0xcb, 0x69, 0x7e, 0x99, 0xf6, 0x36, 0x97,
	0xbd, 0x2a, 0xfd, 0x1b, 0x04, 0xb5, 0x42, 0xab, 0xfe, 0xf6, 0xf9, 0xf5, 0xe1, 0x1c, 0xb9, 0x15,
	0xb6, 0x49, 0xad, 0x9d, 0x41, 0xc6, 0x37, 0xf0, 0x5a, 0xbe, 0xfb, 0xc2, 0xad, 0x90, 0x83, 0xc9,
	0x60, 0x38, 0x69, 0x8c, 0x7b, 0xa3, 0xbb, 0xfe, 0x4d, 0xaf, 0xbb, 0xdd, 0xa1, 0x9d, 0x0b, 0xa7,
	0xe0, 0x74, 0xcb, 0x1c, 0x60, 0xa9, 0x02, 0x9b, 0x08, 0x9b, 0xc7, 0x46, 0x3f, 0x9c, 0x91, 0x26,
	0x21, 0x3e, 0xa8, 0x81, 0x5c, 0xfb, 0x09, 0xce, 0xdc, 0x4a, 0xd1, 0xf1, 0x0e, 0x79, 0x82, 0x33,
	0x13, 0xa9, 0x57, 0x3b, 0xd7, 0x70, 0x44, 0x99, 0x94, 0x7e, 0x0d, 0x6d, 0x89, 0x5d, 0xfb, 0xd8,
	0xab, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd3, 0xd7, 0x84, 0x79, 0xb9, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TkptServiceAPIClient is the client API for TkptServiceAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TkptServiceAPIClient interface {
	GetAbout(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*About, error)
}

type tkptServiceAPIClient struct {
	cc *grpc.ClientConn
}

func NewTkptServiceAPIClient(cc *grpc.ClientConn) TkptServiceAPIClient {
	return &tkptServiceAPIClient{cc}
}

func (c *tkptServiceAPIClient) GetAbout(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*About, error) {
	out := new(About)
	err := c.cc.Invoke(ctx, "/api.tpkt_service.TkptServiceAPI/GetAbout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TkptServiceAPIServer is the server API for TkptServiceAPI service.
type TkptServiceAPIServer interface {
	GetAbout(context.Context, *emptypb.Empty) (*About, error)
}

// UnimplementedTkptServiceAPIServer can be embedded to have forward compatible implementations.
type UnimplementedTkptServiceAPIServer struct {
}

func (*UnimplementedTkptServiceAPIServer) GetAbout(ctx context.Context, req *emptypb.Empty) (*About, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAbout not implemented")
}

func RegisterTkptServiceAPIServer(s *grpc.Server, srv TkptServiceAPIServer) {
	s.RegisterService(&_TkptServiceAPI_serviceDesc, srv)
}

func _TkptServiceAPI_GetAbout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TkptServiceAPIServer).GetAbout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.tpkt_service.TkptServiceAPI/GetAbout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TkptServiceAPIServer).GetAbout(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _TkptServiceAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.tpkt_service.TkptServiceAPI",
	HandlerType: (*TkptServiceAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAbout",
			Handler:    _TkptServiceAPI_GetAbout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tkpt.proto",
}
